version: '3.8'

services:
  fincounter-api:
    image: yuriitsiurpita/fincounter-api
    restart: always
    ports:
      - 2023:2023
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fincounter
    volumes:
      - db-data:/var/lib/postgresql/data

  test-db:
    image: postgres:15.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fincounter

volumes:
  db-data:
    driver: local